import { clipTrailer, iaSources, movie, PD_NOTE, CC_NOTE, type MovieSeed } from "./util";
import type { Title } from "@/lib/types";

/**
 * Public-domain feature films. Every streaming URL points at a verified
 * Internet Archive public-domain item. Runtimes/heights are taken from the
 * Archive's own file metadata so quality labels stay honest.
 */
export const pdMoviesPartA: Title[] = [
  movie({
    slug: "night-of-the-living-dead",
    title: "Night of the Living Dead",
    tagline: "The dead don't sleep.",
    year: 1968,
    runtime: 5753,
    genres: ["horror", "thriller"],
    rating: 7.8,
    popularity: 98,
    director: "George A. Romero",
    cast: [
      { name: "Duane Jones", role: "Ben" },
      { name: "Judith O'Dea", role: "Barbra" },
      { name: "Karl Hardman", role: "Harry Cooper" },
      { name: "Marilyn Eastman", role: "Helen Cooper" },
    ],
    synopsis:
      "A brother and sister visiting their father's grave are attacked by a shambling stranger — the first of the recently dead, now rising across the Pennsylvania countryside. They flee to an isolated farmhouse where a growing band of survivors must barricade themselves in as the ghouls gather outside. George A. Romero's independent shocker redefined the horror genre and remains a landmark of American cinema.",
    releaseDate: "1968-10-01",
    archiveId: "Night.Of.The.Living.Dead_1080p",
    sources: iaSources("Night.Of.The.Living.Dead_1080p", [
      ["NightOfTheLivingDead_PS3.mp4", 1080],
      ["NightOfTheLivingDead_DVD5.mp4", 480],
      ["NightOfTheLivingDead_1080p_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("Night.Of.The.Living.Dead_1080p-0", 420, 35),
    featured: true,
    trending: true,
    topRated: true,
    lumoraPick: true,
    daysAgo: 3,
  }),
  movie({
    slug: "his-girl-friday",
    title: "His Girl Friday",
    tagline: "It's a great picture — and it all happened so fast.",
    year: 1940,
    runtime: 5505,
    genres: ["comedy", "romance"],
    rating: 7.9,
    popularity: 88,
    director: "Howard Hawks",
    cast: [
      { name: "Cary Grant", role: "Walter Burns" },
      { name: "Rosalind Russell", role: "Hildy Johnson" },
      { name: "Ralph Bellamy", role: "Bruce Baldwin" },
    ],
    synopsis:
      "Editor Walter Burns will do anything to keep his star reporter — and ex-wife — Hildy from walking away for a quiet life. His weapon of choice: one last story, a hanging case with political corruption at its core. Delivered at machine-gun pace, Howard Hawks's newsroom screwball remains one of the funniest films ever made.",
    releaseDate: "1940-01-11",
    archiveId: "his_girl_friday",
    sources: iaSources("his_girl_friday", [
      ["his_girl_friday.mp4", 480],
      ["his_girl_friday_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("his_girl_friday-0", 300, 30),
    featured: true,
    trending: true,
    topRated: true,
    daysAgo: 9,
  }),
  movie({
    slug: "the-general",
    title: "The General",
    tagline: "A locomotive, a lady, and the Civil War.",
    year: 1926,
    runtime: 4724,
    genres: ["comedy", "action", "drama"],
    rating: 8.1,
    popularity: 90,
    director: "Buster Keaton, Clyde Bruckman",
    cast: [
      { name: "Buster Keaton", role: "Johnnie Gray" },
      { name: "Marion Mack", role: "Annabelle Lee" },
    ],
    synopsis:
      "Confederate engineer Johnnie Gray loves two things above all: his girl Annabelle and his locomotive, The General. When Union raiders steal both, he sets off alone behind enemy lines in one of silent cinema's most breathtaking chases. Buster Keaton performed his own stunts in this masterpiece of comic precision and physical daring.",
    releaseDate: "1926-12-25",
    archiveId: "The_General_Buster_Keaton",
    sources: iaSources("The_General_Buster_Keaton", [
      ["The_General.mp4", 480],
      ["The_General_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("The_General_Buster_Keaton-0", 600, 30),
    trending: true,
    topRated: true,
    lumoraPick: true,
    silent: true,
    daysAgo: 21,
  }),
  movie({
    slug: "charade",
    title: "Charade",
    tagline: "You can expect the unexpected!",
    year: 1963,
    runtime: 6785,
    genres: ["romance", "comedy", "thriller", "mystery"],
    rating: 7.9,
    popularity: 95,
    director: "Stanley Donen",
    cast: [
      { name: "Cary Grant", role: "Peter Joshua" },
      { name: "Audrey Hepburn", role: "Reggie Lampert" },
      { name: "Walter Matthau", role: "Hamilton Bartholomew" },
      { name: "James Coburn", role: "Tex Panthollow" },
    ],
    synopsis:
      "Returning to Paris to divorce her estranged husband, Reggie Lampert finds him murdered — and a quarter-million dollars missing that everyone believes he stole. Three menacing ex-partners close in, a charming stranger keeps changing his name, and the truth hides in plain sight. Stanley Donen's glossy Hitchcockian caper pairs Cary Grant and Audrey Hepburn at the height of their allure.",
    releaseDate: "1963-12-05",
    archiveId: "charade-1963-cary-grant-audrey-hepburn-comedy-mystery-romance-thriller-full-movie",
    sources: iaSources(
      "charade-1963-cary-grant-audrey-hepburn-comedy-mystery-romance-thriller-full-movie",
      [["Charade_READY.mp4", 720]]
    ),
    trailer: clipTrailer(
      "charade-1963-cary-grant-audrey-hepburn-comedy-mystery-romance-thriller-full-movie-0",
      240,
      35
    ),
    featured: true,
    trending: true,
    topRated: true,
    daysAgo: 1,
  }),
  movie({
    slug: "nosferatu",
    title: "Nosferatu: A Symphony of Horror",
    tagline: "The first vampire of the screen.",
    year: 1922,
    runtime: 5602,
    genres: ["horror", "fantasy"],
    languages: ["de"],
    countries: ["DE"],
    rating: 7.9,
    popularity: 84,
    director: "F. W. Murnau",
    cast: [
      { name: "Max Schreck", role: "Count Orlok" },
      { name: "Gustav von Wangenheim", role: "Thomas Hutter" },
      { name: "Greta Schröder", role: "Ellen Hutter" },
    ],
    synopsis:
      "Estate agent Thomas Hutter travels to the Carpathian mountains to close a deal with the reclusive Count Orlok — and discovers too late that his client is an ancient vampire who has set his sights on Hutter's wife and the port city of Wisborg. Murnau's unauthorized Dracula adaptation is the ur-text of cinematic horror: shadow-draped, feverish, and unforgettable.",
    releaseDate: "1922-03-04",
    archiveId: "Nosferatu_most_complete_version_93_mins.",
    sources: iaSources("Nosferatu_most_complete_version_93_mins.", [
      ["Nosferatu_1922_Symphony_of_Horror_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("Nosferatu_most_complete_version_93_mins.-0", 300, 30),
    featured: true,
    topRated: true,
    silent: true,
    daysAgo: 30,
  }),
  movie({
    slug: "the-cabinet-of-dr-caligari",
    title: "The Cabinet of Dr. Caligari",
    tagline: "You must become Caligari!",
    year: 1920,
    runtime: 4298,
    genres: ["horror", "mystery", "thriller"],
    languages: ["de"],
    countries: ["DE"],
    rating: 8.1,
    popularity: 78,
    director: "Robert Wiene",
    cast: [
      { name: "Werner Krauss", role: "Dr. Caligari" },
      { name: "Conrad Veidt", role: "Cesare" },
      { name: "Lil Dagover", role: "Jane Olsen" },
    ],
    synopsis:
      "At a travelling fair in a town of impossible angles, the showman Dr. Caligari exhibits Cesare, a somnambulist who answers questions about the future — including the hour of a man's death. When murders follow the prophecy, Francis suspects the hypnotist and his sleepwalking servant. The defining work of German Expressionism, painted in jagged shadows and madness.",
    releaseDate: "1920-02-26",
    archiveId: "thecabinetofdrcaligari",
    sources: iaSources("thecabinetofdrcaligari", [["KabinettDesDoktorCaligariDas_512kb.mp4", 240]]),
    trailer: clipTrailer("thecabinetofdrcaligari-0", 200, 30),
    topRated: true,
    lumoraPick: true,
    silent: true,
    daysAgo: 33,
  }),
  movie({
    slug: "detour",
    title: "Detour",
    tagline: "Fate takes the wheel.",
    year: 1945,
    runtime: 4058,
    genres: ["thriller", "drama", "crime"],
    rating: 7.2,
    popularity: 66,
    director: "Edgar G. Ulmer",
    cast: [
      { name: "Tom Neal", role: "Al Roberts" },
      { name: "Ann Savage", role: "Vera" },
      { name: "Claudia Drake", role: "Sue Harvey" },
    ],
    synopsis:
      "Piano player Al Roberts hitchhikes from New York to Los Angeles to reunite with his singer girlfriend — but a roadside accident and a case of mistaken identity spiral into blackmail and murder on the open highway. Shot in six days on poverty row, Edgar G. Ulmer's Detour is film noir distilled to its purest, most paranoid essence.",
    releaseDate: "1945-11-30",
    archiveId: "Detour",
    sources: iaSources("Detour", [
      ["Detour.mp4", 480],
      ["Detour_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("Detour-0", 400, 30),
    trending: true,
    daysAgo: 12,
  }),
  movie({
    slug: "meet-john-doe",
    title: "Meet John Doe",
    tagline: "A nation holds its breath for one man's decision.",
    year: 1941,
    runtime: 7371,
    genres: ["drama", "romance", "comedy"],
    rating: 7.6,
    popularity: 70,
    director: "Frank Capra",
    cast: [
      { name: "Gary Cooper", role: "John Doe / Long John Willoughby" },
      { name: "Barbara Stanwyck", role: "Ann Mitchell" },
      { name: "Edward Arnold", role: "D. B. Norton" },
    ],
    synopsis:
      "Fired columnist Ann Mitchell invents a letter from a 'John Doe' threatening to jump from city hall on Christmas Eve in protest of the modern world — and when the public embraces the fiction, a media empire turns a homeless ballplayer into a national movement with cynical ends. Frank Capra's dark-edged fable about populism, press and conscience stars Gary Cooper and Barbara Stanwyck.",
    releaseDate: "1941-03-07",
    archiveId: "meet_john_doe",
    sources: iaSources("meet_john_doe", [
      ["meet_john_doe.mp4", 480],
      ["meet_john_doe_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("meet_john_doe-0", 500, 30),
    daysAgo: 18,
  }),
  movie({
    slug: "the-stranger",
    title: "The Stranger",
    tagline: "No man can hide from his past.",
    year: 1946,
    runtime: 5643,
    genres: ["thriller", "mystery", "drama", "crime"],
    rating: 7.3,
    popularity: 72,
    director: "Orson Welles",
    cast: [
      { name: "Orson Welles", role: "Charles Rankin / Franz Kindler" },
      { name: "Edward G. Robinson", role: "Mr. Wilson" },
      { name: "Loretta Young", role: "Mary Longstreet" },
    ],
    synopsis:
      "A war-crimes investigator follows the trail of a fugitive Nazi architect to a quiet Connecticut town, where the suspect has reinvented himself as a respected teacher — and is about to marry a Supreme Court justice's daughter. Orson Welles directs and stars in a taut cat-and-mouse thriller that builds to a deadly confrontation in a clock tower.",
    releaseDate: "1946-05-25",
    archiveId: "the_stranger_1946",
    sources: iaSources("the_stranger_1946", [["the_stranger_1946.mp4", 932]]),
    trailer: clipTrailer("the_stranger_1946-0", 350, 30),
    trending: true,
    daysAgo: 6,
  }),
  movie({
    slug: "house-on-haunted-hill",
    title: "House on Haunted Hill",
    tagline: "Twelve thousand dollars to survive the night.",
    year: 1959,
    runtime: 4483,
    genres: ["horror", "mystery"],
    rating: 7.3,
    popularity: 80,
    director: "William Castle",
    cast: [
      { name: "Vincent Price", role: "Frederick Loren" },
      { name: "Carol Ohmart", role: "Annabelle Loren" },
      { name: "Alan Marshal", role: "Dr. David Trent" },
    ],
    synopsis:
      "Eccentric millionaire Frederick Loren offers five guests $10,000 each if they can last one night inside a mansion with a history of murder — locked in, armed with a pistol, and alone with whatever prowls the halls. William Castle's haunted-house showpiece, hosted by Vincent Price at his most deliciously sardonic.",
    releaseDate: "1959-02-17",
    archiveId: "The_House_On_Haunted_Hill",
    sources: iaSources("The_House_On_Haunted_Hill", [
      ["The_House_On_Haunted_Hill.mp4", 480],
      ["The_House_On_Haunted_Hill_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("The_House_On_Haunted_Hill-0", 260, 30),
    trending: true,
    lumoraPick: true,
    daysAgo: 4,
  }),
  movie({
    slug: "carnival-of-souls",
    title: "Carnival of Souls",
    tagline: "Some places call to you — and won't let go.",
    year: 1962,
    runtime: 4979,
    genres: ["horror", "mystery", "drama"],
    rating: 7.0,
    popularity: 64,
    director: "Herk Harvey",
    cast: [
      { name: "Candace Hilligoss", role: "Mary Henry" },
      { name: "Frances Feist", role: "Linda Mason" },
      { name: "Sidney Berger", role: "John Linden" },
    ],
    synopsis:
      "After surviving a drag-race plunge into a river, church organist Mary Henry drifts to Salt Lake City for a fresh start — but finds herself drawn, trance-like, to an abandoned pavilion on the shore of the Great Salt Lake, and increasingly out of step with the living. Herk Harvey's low-budget tone poem of dread influenced everything from Night of the Living Dead to Mulholland Drive.",
    releaseDate: "1962-09-26",
    archiveId: "carnival_of_souls",
    sources: iaSources("carnival_of_souls", [
      ["carnival_of_souls.mp4", 240],
      ["carnival_of_souls_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("carnival_of_souls-0", 320, 30),
    daysAgo: 15,
  }),
  movie({
    slug: "plan-9-from-outer-space",
    title: "Plan 9 from Outer Space",
    tagline: "Ghoulies and ghosties and long-leggedy beasties…",
    year: 1959,
    runtime: 4700,
    genres: ["scifi", "horror", "cult"],
    rating: 4.0,
    popularity: 76,
    director: "Edward D. Wood Jr.",
    cast: [
      { name: "Bela Lugosi", role: "The Ghoul" },
      { name: "Tor Johnson", role: "Inspector Clay" },
      { name: "Vampira", role: "The Ghoul Girl" },
      { name: "Gregory Walcott", role: "Jeff Trent" },
    ],
    synopsis:
      "Aliens resurrecting the recently dead as part of 'Plan 9' descend on San Fernando Valley while flying saucers — clearly on strings — menace the skies. Ed Wood's legendariously earnest fiasco is beloved precisely for its glorious incompetence: cardboard tombstones, daylight-visible boom mics, and Bela Lugosi's final, posthumous appearance.",
    releaseDate: "1959-07-22",
    archiveId: "plan-9-from-outer-space",
    sources: iaSources("plan-9-from-outer-space", [["plan-9-from-outer-space.mp4", 240]]),
    trailer: clipTrailer("plan-9-from-outer-space-0", 180, 30),
    trending: true,
    daysAgo: 8,
  }),
  movie({
    slug: "the-39-steps",
    title: "The 39 Steps",
    tagline: "Hitchcock's first masterpiece of suspense.",
    year: 1935,
    runtime: 5180,
    genres: ["thriller", "mystery"],
    countries: ["GB"],
    rating: 7.7,
    popularity: 82,
    director: "Alfred Hitchcock",
    cast: [
      { name: "Robert Donat", role: "Richard Hannay" },
      { name: "Madeleine Carroll", role: "Pamela" },
      { name: "Lucie Mannheim", role: "Annabella Smith" },
    ],
    synopsis:
      "A chance encounter at a London music hall leaves ordinary visitor Richard Hannay with a murdered spy's secret, a map of the Highlands, and the police on his tail. Hitchcock's breakneck John Buchan adaptation perfected the wrong-man formula — and the handcuffed chemistry between Robert Donat and Madeleine Carroll — that would define his entire career.",
    releaseDate: "1935-06-06",
    archiveId: "the_39_steps_1935",
    sources: iaSources("the_39_steps_1935", [["the_39_steps_1935.mp4", 720]]),
    trailer: clipTrailer("the_39_steps_1935-0", 280, 30),
    topRated: true,
    daysAgo: 25,
  }),
  movie({
    slug: "the-lady-vanishes",
    title: "The Lady Vanishes",
    tagline: "She was there — and then she wasn't.",
    year: 1938,
    runtime: 5781,
    genres: ["mystery", "thriller", "comedy"],
    countries: ["GB"],
    rating: 7.8,
    popularity: 79,
    director: "Alfred Hitchcock",
    cast: [
      { name: "Margaret Lockwood", role: "Iris Henderson" },
      { name: "Michael Redgrave", role: "Gilbert" },
      { name: "Dame May Whitty", role: "Miss Froy" },
    ],
    synopsis:
      "Aboard a train crossing a fictional central Europe, young socialite Iris befriends elderly governess Miss Froy — who promptly disappears while every other passenger insists she never existed. Hitchcock's pre-war caper blends comic turn, spy intrigue and gaslighting dread in one perfectly engineered ride, with a finale of gunfire and steam.",
    releaseDate: "1938-11-01",
    archiveId: "the-lady-vanishes-1938",
    sources: iaSources("the-lady-vanishes-1938", [["The Lady Vanishes (1938).mp4", 480]]),
    trailer: clipTrailer("the-lady-vanishes-1938-0", 300, 30),
    topRated: true,
    trending: true,
    daysAgo: 5,
  }),
  movie({
    slug: "the-phantom-of-the-opera",
    title: "The Phantom of the Opera",
    tagline: "Beneath the opera house waits a shadow with a face of horror.",
    year: 1925,
    runtime: 6389,
    genres: ["horror", "romance", "drama"],
    rating: 7.6,
    popularity: 71,
    director: "Rupert Julian",
    cast: [
      { name: "Lon Chaney", role: "Erik, the Phantom" },
      { name: "Mary Philbin", role: "Christine Daaé" },
      { name: "Norman Kerry", role: "Raoul" },
    ],
    synopsis:
      "A disfigured genius haunting the cellars of the Paris Opera terrorizes the company into casting his beloved protégée Christine — until her unmasking becomes one of cinema's most famous shocks. Lon Chaney designed his own skull-like makeup for this lavish silent spectacle, complete with Technicolor ballroom sequences.",
    releaseDate: "1925-09-06",
    archiveId: "ThePhantomoftheOpera",
    sources: iaSources("ThePhantomoftheOpera", [["Phantom_of_the_Opera_512kb.mp4", 240]]),
    trailer: clipTrailer("ThePhantomoftheOpera-0", 500, 30),
    silent: true,
    daysAgo: 28,
  }),
  movie({
    slug: "the-scarlet-claw",
    title: "The Scarlet Claw",
    tagline: "Sherlock Holmes vs. the terror of the moors.",
    year: 1944,
    runtime: 4256,
    genres: ["mystery", "crime", "thriller"],
    countries: ["GB", "US"],
    rating: 7.4,
    popularity: 68,
    director: "Roy William Neill",
    cast: [
      { name: "Basil Rathbone", role: "Sherlock Holmes" },
      { name: "Nigel Bruce", role: "Dr. Watson" },
      { name: "Gerald Hamer", role: "Emory Brisson" },
    ],
    synopsis:
      "A glowing phantom stalking the Canadian marshlands kills with a wound like a wild beast's — and Sherlock Holmes suspects a very human hand behind the supernatural legend. Widely considered the best of the Rathbone–Bruce series, a fog-drenched mystery with one of the detective's most menacing adversaries.",
    releaseDate: "1944-05-26",
    archiveId: "the-scarlet-claw",
    sources: iaSources("the-scarlet-claw", [["The Scarlet Claw.mp4", 480]]),
    trailer: clipTrailer("the-scarlet-claw-0", 260, 30),
    daysAgo: 20,
  }),
  movie({
    slug: "d-o-a",
    title: "D.O.A.",
    tagline: "A man has twenty-four hours to solve his own murder.",
    year: 1950,
    runtime: 5005,
    genres: ["crime", "thriller", "mystery"],
    rating: 7.2,
    popularity: 62,
    director: "Rudolph Maté",
    cast: [
      { name: "Edmond O'Brien", role: "Frank Bigelow" },
      { name: "Pamela Britton", role: "Paula Gibson" },
      { name: "Luther Adler", role: "Majak" },
    ],
    synopsis:
      "Accountant Frank Bigelow walks into a police station to report a murder — his own. Poisoned with a substance that leaves him hours to live, he crisscrosses San Francisco and Los Angeles hunting the person who killed him. Rudolph Maté's noir opens with one of cinema's great hooks and never lets the pressure drop.",
    releaseDate: "1950-04-30",
    archiveId: "DOA1950",
    sources: iaSources("DOA1950", [["DOA (1950).mp4", 480]]),
    trailer: clipTrailer("DOA1950-0", 300, 30),
    daysAgo: 14,
  }),
  movie({
    slug: "scrooge",
    title: "Scrooge",
    tagline: "Charles Dickens' A Christmas Carol — the definitive screen version.",
    year: 1951,
    runtime: 5192,
    genres: ["drama", "fantasy", "family"],
    countries: ["GB"],
    rating: 8.1,
    popularity: 74,
    director: "Brian Desmond Hurst",
    cast: [
      { name: "Alastair Sim", role: "Ebenezer Scrooge" },
      { name: "Michael Hordern", role: "Jacob Marley" },
      { name: "Kathleen Harrison", role: "Mrs. Dilber" },
    ],
    synopsis:
      "On the bitterest Christmas Eve in London, miser Ebenezer Scrooge is visited by the ghost of his partner Marley, then by three spirits who walk him through the shadows of his past, present and yet-to-come. Alastair Sim's transformation from skinflint to joyful benefactor anchors what many consider the greatest of all Carol adaptations.",
    releaseDate: "1951-10-31",
    archiveId: "a-christmas-carol-scrooge-1951",
    sources: iaSources("a-christmas-carol-scrooge-1951", [["A Christmas Carol Scrooge 1951.mp4", 720]]),
    // This Archive item ships an authentic period trailer file.
    trailer: { kind: "file", url: "https://archive.org/download/a-christmas-carol-scrooge-1951/0%20Trailer.mp4" },
    topRated: true,
    daysAgo: 10,
  }),
];
