import { clipTrailer, iaSources, movie, CC_NOTE, type MovieSeed } from "./util";
import type { StreamingSource, Title } from "@/lib/types";

const CC_ATTR = "© Blender Foundation — Creative Commons Attribution 3.0";

/** Public-domain features, part B. */
export const pdMoviesPartB: Title[] = [
  movie({
    slug: "penny-serenade",
    title: "Penny Serenade",
    year: 1941,
    runtime: 7147,
    genres: ["romance", "drama"],
    rating: 7.1,
    popularity: 58,
    director: "George Stevens",
    cast: [
      { name: "Cary Grant", role: "Roger Adams" },
      { name: "Irene Dunne", role: "Julie Gardiner" },
      { name: "Beulah Bondi", role: "Miss Oliver" },
    ],
    synopsis:
      "As a marriage founders, Julie plays the records that trace her courtship with newspaperman Roger — each song a chapter of love, adoption, loss and renewal. Cary Grant earned his first Oscar nomination in George Stevens's tender, bittersweet romance, structured as a stack of 78-rpm memories.",
    releaseDate: "1941-04-24",
    archiveId: "PennySerenade",
    sources: iaSources("PennySerenade", [
      ["PennySerenadePresentedByMoviePowder.mp4", 480],
      ["PennySerenadePresentedByMoviePowder_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("PennySerenade-0", 400, 30),
    daysAgo: 16,
  }),
  movie({
    slug: "royal-wedding",
    title: "Royal Wedding",
    year: 1951,
    runtime: 5497,
    genres: ["musical", "romance", "comedy"],
    rating: 6.6,
    popularity: 55,
    director: "Stanley Donen",
    cast: [
      { name: "Fred Astaire", role: "Tom Bowen" },
      { name: "Jane Powell", role: "Ellen Bowen" },
      { name: "Peter Lawford", role: "Lord John Brindale" },
    ],
    synopsis:
      "A brother-and-sister song-and-dance act takes their show to London during the week of Princess Elizabeth's 1951 wedding — and both fall in love along the way. Stanley Donen directs Fred Astaire in this bright Technicolor musical, famous for the gravity-defying 'You're All the World to Me' ceiling-and-wall dance.",
    releaseDate: "1951-03-08",
    archiveId: "royal_wedding",
    sources: iaSources("royal_wedding", [
      ["royal_wedding.mp4", 480],
      ["royal_wedding_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("royal_wedding-0", 350, 30),
    daysAgo: 22,
  }),
  movie({
    slug: "mclintock",
    title: "McLintock!",
    year: 1963,
    runtime: 7607,
    genres: ["western", "comedy", "romance"],
    rating: 7.0,
    popularity: 63,
    director: "Andrew V. McLaglen",
    cast: [
      { name: "John Wayne", role: "G. W. McLintock" },
      { name: "Maureen O'Hara", role: "Katherine McLintock" },
      { name: "Yvonne De Carlo", role: "Louise Warren" },
      { name: "Patrick Wayne", role: "Devlin Warren" },
    ],
    synopsis:
      "Cattle baron G. W. McLintock rules his frontier town with good humour and iron will — until his estranged wife returns to claim their daughter and upend everything. John Wayne and Maureen O'Hara trade barbs (and a legendary mudhole brawl) in this boisterous western comedy loosely riffing on The Taming of the Shrew.",
    releaseDate: "1963-11-13",
    archiveId: "mclintok_widescreen",
    sources: iaSources("mclintok_widescreen", [
      ["McLintock.mp4", 276],
      ["McLintock_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("mclintok_widescreen-0", 600, 30),
    daysAgo: 26,
  }),
  movie({
    slug: "beat-the-devil",
    title: "Beat the Devil",
    year: 1953,
    runtime: 5357,
    genres: ["adventure", "comedy", "crime"],
    countries: ["GB", "US"],
    rating: 6.0,
    popularity: 50,
    director: "John Huston",
    cast: [
      { name: "Humphrey Bogart", role: "Billy Dannreuther" },
      { name: "Jennifer Jones", role: "Mrs. Gwendolyn Chelm" },
      { name: "Gina Lollobrigida", role: "Maria Dannreuther" },
      { name: "Peter Lorre", role: "Julius O'Hara" },
    ],
    synopsis:
      "A stranded crowd of misfits — a crooked trio, a British couple and a bankrupt American — schemes over uranium claims on the Italian Riviera before a doomed voyage to Africa. John Huston's send-up of his own African Queen adventure, improvised daily with Truman Capote, is a cult treasure of deadpan absurdity.",
    releaseDate: "1953-11-23",
    archiveId: "BeatTheDevil1953",
    sources: iaSources("BeatTheDevil1953", [
      ["BeatTheDevil1954.mp4", 360],
      ["BeatTheDevil1954_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("BeatTheDevil1953-0", 300, 30),
    daysAgo: 34,
  }),
  movie({
    slug: "santa-claus-conquers-the-martians",
    title: "Santa Claus Conquers the Martians",
    year: 1964,
    runtime: 4857,
    genres: ["family", "scifi", "comedy", "cult"],
    rating: 2.6,
    popularity: 57,
    director: "Nicholas Webster",
    cast: [
      { name: "John Call", role: "Santa Claus" },
      { name: "Leonard Hicks", role: "Momar" },
      { name: "Vincent Beck", role: "Voldar" },
      { name: "Bill McCutcheon", role: "Dropo" },
    ],
    synopsis:
      "When Martian children become addicted to Earth television — especially Santa Claus — their leaders kidnap St. Nick to start a toy factory on Mars. A holiday B-movie so gloriously cheap (a cardboard robot, visible zippers on the polar bear) that it became a beloved seasonal-camp tradition.",
    releaseDate: "1964-11-14",
    archiveId: "SantaClausConquerstheMartians1964",
    sources: iaSources("SantaClausConquerstheMartians1964", [
      ["SantaClausConquerstheMartians1964.mp4", 480],
    ]),
    trailer: clipTrailer("SantaClausConquerstheMartians1964-0", 200, 30),
    daysAgo: 40,
  }),
  movie({
    slug: "manos-the-hands-of-fate",
    title: "Manos: The Hands of Fate",
    year: 1966,
    runtime: 4121,
    genres: ["horror", "cult"],
    rating: 2.0,
    popularity: 52,
    director: "Harold P. Warren",
    cast: [
      { name: "Harold P. Warren", role: "Torgo" },
      { name: "Tom Neyman", role: "The Master" },
      { name: "John Reynolds", role: "Michael" },
    ],
    synopsis:
      "A lost family on a southwest detour stumbles into the domain of a satanic caretaker named Torgo — 'The Master is not pleased' — in a film shot on a silent wind-up 16mm camera with dubbed audio. Infamously resurrected by Mystery Science Theater 3000, Manos is the Mount Rushmore of so-bad-it's-essential cinema.",
    releaseDate: "1966-11-15",
    archiveId: "manos_the_hands_of_fate",
    sources: iaSources("manos_the_hands_of_fate", [
      ["Manos-The.Hands.of.Fate.mp4", 360],
      ["Manos-The.Hands.of.Fate_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("manos_the_hands_of_fate-0", 250, 30),
    daysAgo: 44,
  }),
  movie({
    slug: "gullivers-travels",
    title: "Gulliver's Travels",
    year: 1939,
    runtime: 4360,
    genres: ["animation", "family", "adventure", "fantasy"],
    rating: 6.7,
    popularity: 60,
    director: "Dave Fleischer",
    cast: [
      { name: "Jessica Dragonette", role: "Princess Glory (voice)" },
      { name: "Lanny Ross", role: "Prince David (voice)" },
      { name: "Pinto Colvig", role: "Gabby (voice)" },
    ],
    synopsis:
      "Shipwrecked on Lilliput, traveller Lemuel Gulliver becomes the gentle giant who must stop a war between two tiny kingdoms over the wording of a royal wedding song. The Fleischer Studios' first feature — Disney's Snow White answered by a lush, jazz-inflected animated classic, home of the scene-stealing town crier Gabby.",
    releaseDate: "1939-12-22",
    archiveId: "GulliversTravels",
    sources: iaSources("GulliversTravels", [
      ["gullivers_travels1939.mp4", 480],
      ["gullivers_travels1939_256kb.mp4", 240],
    ]),
    trailer: clipTrailer("GulliversTravels-0", 300, 30),
    daysAgo: 36,
  }),
  movie({
    slug: "reefer-madness",
    title: "Reefer Madness",
    year: 1936,
    runtime: 4098,
    genres: ["drama", "comedy", "cult"],
    rating: 5.6,
    popularity: 56,
    director: "Louis J. Gasnier",
    cast: [
      { name: "Dorothy Short", role: "Mary Lane" },
      { name: "Kenneth Craig", role: "Bill Harper" },
      { name: "Lillian Miles", role: "Mae Coleman" },
    ],
    synopsis:
      "One drag on the 'killer weed' sends upstanding teens careening into jazz-fuelled mania, madness and murder — or so this 1930s morality film insists with total sincerity. Made as anti-marijuana propaganda, rediscovered as unintentional comedy: the most famous cautionary tale in American exploitation cinema.",
    releaseDate: "1936-04-20",
    archiveId: "reefer_madness1938",
    sources: iaSources("reefer_madness1938", [
      ["reefer_madness1938.mp4", 480],
      ["reefer_madness1938_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("reefer_madness1938-0", 220, 30),
    daysAgo: 42,
  }),
  movie({
    slug: "the-little-shop-of-horrors",
    title: "The Little Shop of Horrors",
    year: 1960,
    runtime: 4351,
    genres: ["comedy", "horror", "cult"],
    rating: 6.2,
    popularity: 61,
    director: "Roger Corman",
    cast: [
      { name: "Jonathan Haze", role: "Seymour Krelborn" },
      { name: "Jackie Joseph", role: "Audrey Fulquard" },
      { name: "Mel Welles", role: "Gravis Mushnick" },
      { name: "Jack Nicholson", role: "Wilbur Force" },
    ],
    synopsis:
      "Skid Row florist's assistant Seymour cultivates a strange talking plant that brings customers flooding in — and demands increasingly personal 'feedings' to keep blooming. Roger Corman shot this black comedy (with a young Jack Nicholson as a masochistic dental patient) in two days on leftover sets; it grew into an off-Broadway legend and two feature remakes.",
    releaseDate: "1960-09-14",
    archiveId: "Little_ShopOf_Horrors.avi",
    sources: iaSources("Little_ShopOf_Horrors.avi", [
      ["The_Little_Shop_of_Horrors.mp4", 480],
      ["The_Little_Shop_of_Horrors_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("Little_ShopOf_Horrors.avi-0", 240, 30),
    daysAgo: 24,
  }),
  movie({
    slug: "steamboat-bill-jr",
    title: "Steamboat Bill, Jr.",
    year: 1928,
    runtime: 4148,
    genres: ["comedy", "action", "romance"],
    rating: 7.8,
    popularity: 65,
    director: "Charles Reisner",
    cast: [
      { name: "Buster Keaton", role: "William Canfield Jr." },
      { name: "Ernest Torrence", role: "Steamboat Bill" },
      { name: "Marion Byron", role: "Kitty King" },
    ],
    synopsis:
      "A college sissy arrives in his riverboat-captain father's Mississippi town — and promptly falls for the daughter of the rival steamboat king. Buster Keaton's final independent feature contains his most famous stunt: a two-ton house facade falling around him, timed to an open window. He performed it for real.",
    releaseDate: "1928-05-12",
    archiveId: "steamboat_bill_ipod",
    sources: iaSources("steamboat_bill_ipod", [
      ["steamboat_bill.mp4", 480],
      ["steamboat_bill_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("steamboat_bill_ipod-0", 500, 30),
    topRated: true,
    silent: true,
    daysAgo: 31,
  }),
  movie({
    slug: "robot-monster",
    title: "Robot Monster",
    year: 1953,
    runtime: 3756,
    genres: ["scifi", "cult", "horror"],
    rating: 2.9,
    popularity: 48,
    director: "Phil Tucker",
    cast: [
      { name: "George Nader", role: "Glen" },
      { name: "George Barrows", role: "Ro-Man" },
    ],
    synopsis:
      "A gorilla in a diving helmet with calculator eyes — Ro-Man, the Robot Monster — stalks the last human family after wiping out civilization with his 'calcinator death ray'. Shot in 3D on four days for $16,000, Robot Monster is a hall-of-fame disaster whose strange dream logic and tragic tone have charmed cult audiences for decades.",
    releaseDate: "1953-06-02",
    archiveId: "robot-monster-1953",
    sources: iaSources("robot-monster-1953", [["Robot Monster (1953).mp4", 360]]),
    trailer: clipTrailer("robot-monster-1953-0", 200, 30),
    daysAgo: 46,
  }),
  movie({
    slug: "the-brain-that-wouldnt-die",
    title: "The Brain That Wouldn't Die",
    year: 1962,
    runtime: 4268,
    genres: ["horror", "scifi", "cult"],
    rating: 4.2,
    popularity: 49,
    director: "Joseph Green",
    cast: [
      { name: "Jason Evers", role: "Dr. Bill Cortner" },
      { name: "Virginia Leith", role: "Jan Compton" },
      { name: "Bruce Kerr", role: "Dr. Kurtz" },
    ],
    synopsis:
      "After a car accident decapitates his fiancée, a brilliant surgeon keeps her head alive on a laboratory platter — and begins hunting the city for a 'perfect' new body while the brain plots revenge. A drive-in staple of mad-science cinema with genuinely unsettling existential horror at its core.",
    releaseDate: "1962-08-01",
    archiveId: "the_brain_that_wouldnt_die",
    sources: iaSources("the_brain_that_wouldnt_die", [
      ["the_brain_that_wouldnt_die.mp4", 480],
      ["the_brain_that_wouldnt_die_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("the_brain_that_wouldnt_die-0", 260, 30),
    daysAgo: 48,
  }),
  movie({
    slug: "the-terror",
    title: "The Terror",
    year: 1963,
    runtime: 4743,
    genres: ["horror", "mystery"],
    rating: 5.0,
    popularity: 46,
    director: "Roger Corman",
    cast: [
      { name: "Boris Karloff", role: "Baron Victor Frederick" },
      { name: "Jack Nicholson", role: "Lt. Andre Duvalier" },
      { name: "Sandra Knight", role: "Helene" },
    ],
    synopsis:
      "In 1806, a young Napoleonic officer follows a mysterious woman along the Baltic coast to the crumbling castle of Baron von Leppe — where a hypnotized beauty, a guilty nobleman and a vengeful witch entwine. Roger Corman's gothic fever dream, famous for using leftover sets and giving a 25-year-old Jack Nicholson his first lead.",
    releaseDate: "1963-02-25",
    archiveId: "TheTerror1963",
    sources: iaSources("TheTerror1963", [["TheTerror_512kb.mp4", 240]]),
    trailer: clipTrailer("TheTerror1963-0", 300, 30),
    daysAgo: 50,
  }),
  movie({
    slug: "the-last-man-on-earth",
    title: "The Last Man on Earth",
    year: 1964,
    runtime: 5204,
    genres: ["scifi", "horror", "drama"],
    countries: ["IT", "US"],
    rating: 6.8,
    popularity: 67,
    director: "Ubaldo Ragona, Sidney Salkow",
    cast: [
      { name: "Vincent Price", role: "Dr. Robert Morgan" },
      { name: "Franca Bettoia", role: "Ruth Collins" },
      { name: "Emma Danieli", role: "Virginia Morgan" },
    ],
    synopsis:
      "A plague has turned humanity into vampire-like creatures, and Dr. Robert Morgan may be the only immune survivor — by day he hunts them with stakes and mirrors, by night he barricades himself against their howls. The first (and most faithful) adaptation of Richard Matheson's I Am Legend, and a direct ancestor of Night of the Living Dead.",
    releaseDate: "1964-03-08",
    archiveId: "TheLastManOnEarth1964_201808",
    sources: iaSources("TheLastManOnEarth1964_201808", [["The Last Man on Earth (1964).mp4", 360]]),
    trailer: clipTrailer("TheLastManOnEarth1964_201808-0", 300, 30),
    trending: true,
    daysAgo: 7,
  }),
  movie({
    slug: "dementia-13",
    title: "Dementia 13",
    year: 1963,
    runtime: 4860,
    genres: ["horror", "thriller", "mystery"],
    rating: 6.6,
    popularity: 54,
    director: "Francis Ford Coppola",
    cast: [
      { name: "William Campbell", role: "Richard Haloran" },
      { name: "Luana Anders", role: "Louise Haloran" },
      { name: "Bart Patton", role: "Billy Haloran" },
    ],
    synopsis:
      "When her husband dies suddenly, Louise Haloran fakes his survival to keep her claim on the family estate — arriving in Ireland for a séance-lit reunion where an axe murderer stalks the Haloran clan. Francis Ford Coppola's directorial debut, shot guerrilla-style in nine days for Roger Corman, is stylish gothic dread on a shoestring.",
    releaseDate: "1963-09-25",
    archiveId: "Dementia13_201411",
    sources: iaSources("Dementia13_201411", [["Dementia13.mp4", 360]]),
    trailer: clipTrailer("Dementia13_201411-0", 400, 30),
    daysAgo: 11,
  }),
  movie({
    slug: "nanook-of-the-north",
    title: "Nanook of the North",
    year: 1922,
    runtime: 4683,
    genres: ["documentary", "drama"],
    countries: ["US", "CA"],
    rating: 7.4,
    popularity: 47,
    director: "Robert J. Flaherty",
    cast: [{ name: "Allakariallak (Nanook)", role: "Himself" }],
    synopsis:
      "A year in the life of an Inuk hunter and his family in the Canadian Arctic — walrus hunts, igloo-building, and the patient struggle against cold and hunger. Robert Flaherty's landmark is generally considered the first feature-length documentary, blending real footage with staged scenes in a tradition that shaped the genre itself.",
    releaseDate: "1922-06-11",
    archiveId: "NanookOfTheNorth-HD",
    sources: iaSources("NanookOfTheNorth-HD", [["nanook of the north.mp4", 480]]),
    trailer: clipTrailer("NanookOfTheNorth-HD-0", 240, 30),
    silent: true,
    daysAgo: 52,
  }),
  movie({
    slug: "man-with-a-movie-camera",
    title: "Man with a Movie Camera",
    year: 1929,
    runtime: 4009,
    genres: ["documentary", "drama"],
    languages: ["ru"],
    countries: ["SU"],
    rating: 8.4,
    popularity: 51,
    director: "Dziga Vertov",
    cast: [{ name: "Mikhail Kaufman", role: "The cameraman" }],
    synopsis:
      "From dawn to dusk across Soviet cities, a cameraman films life while the film itself fractures, freezes, speeds and double-exposes before your eyes. Dziga Vertov's city symphony is arguably the most formally inventive documentary ever made — a manifesto that cinema can see the world better than the human eye.",
    releaseDate: "1929-01-08",
    archiveId: "ChelovekskinoapparatomManWithAMovieCamera",
    sources: iaSources("ChelovekskinoapparatomManWithAMovieCamera", [
      ["Chelovek_s_kino-apparatom_512kb.mp4", 240],
    ]),
    trailer: clipTrailer("ChelovekskinoapparatomManWithAMovieCamera-0", 200, 30),
    topRated: true,
    silent: true,
    daysAgo: 54,
  }),
];

/**
 * LUMORA demo showcase — open movies by the Blender Foundation (CC BY 3.0).
 * These are clearly flagged `contentTier: "demo"` and badged in the UI so
 * demo content is never confused with rights-cleared production catalog.
 */
export const demoMovies: Title[] = [
  movie({
    slug: "big-buck-bunny",
    title: "Big Buck Bunny",
    tagline: "An open-movie classic by the Blender Foundation.",
    year: 2008,
    runtime: 597,
    genres: ["animation", "comedy", "family"],
    rating: 7.5,
    popularity: 92,
    contentRating: "PG",
    director: "Sacha Goedegebure",
    cast: [
      { name: "Big Buck Bunny", role: "Himself" },
      { name: "Frank the Rabbit", role: "Antagonist" },
    ],
    synopsis:
      "A gentle giant of a rabbit enjoys a peaceful morning in the forest until three bullies pick on the wrong lagomorph — and his elaborate, Rube Goldberg-style revenge begins. The Blender Foundation's beloved open movie, used worldwide to test streaming pipelines (this copy plays through our adaptive HLS demo).",
    releaseDate: "2008-04-10",
    archiveId: "BigBuckBunny_124",
    sources: [
      {
        id: "bbb-hls",
        quality: "Adaptive (HLS)",
        type: "hls",
        url: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
        rights: "cc-licensed",
        attribution: CC_ATTR,
      },
      {
        id: "bbb-mp4",
        quality: "360p",
        height: 360,
        type: "mp4",
        url: "https://archive.org/download/BigBuckBunny_124/Content/big_buck_bunny_720p_surround.mp4",
        rights: "cc-licensed",
        attribution: CC_ATTR,
      },
    ],
    subtitles: [
      { id: "bbb-en", lang: "en", label: "English (demo captions)", url: "/subs/bbb-en.vtt", kind: "captions", default: true },
    ],
    trailer: clipTrailer("bbb-mp4", 20, 40),
    featured: true,
    trending: true,
    newRelease: true,
    rightsNote: CC_NOTE,
    contentTier: "demo",
    daysAgo: 2,
  }),
  movie({
    slug: "sintel",
    title: "Sintel",
    tagline: "A lonely girl's journey across a broken world.",
    year: 2010,
    runtime: 888,
    genres: ["animation", "fantasy", "adventure", "drama"],
    rating: 7.6,
    popularity: 86,
    contentRating: "PG-13",
    director: "Colin Tilley",
    cast: [
      { name: "Halina Reijn", role: "Sintel (voice)" },
      { name: "Thom Hoffman", role: "Shaman (voice)" },
    ],
    synopsis:
      "A wandering warrior named Sintel tracks the baby dragon she once rescued and lost — crossing deserts, war-torn cities and frozen peaks in a quest with a devastating final reveal. The Blender Foundation's third open movie remains one of the most emotionally ambitious animated shorts ever produced.",
    releaseDate: "2010-09-27",
    archiveId: "Sintel",
    sources: iaSources(
      "Sintel",
      [
        ["sintel-2048-stereo.mp4", 872],
        ["sintel-2048-stereo_512kb.mp4", 240],
      ],
      "cc-licensed",
      CC_ATTR
    ),
    subtitles: [
      { id: "sintel-en", lang: "en", label: "English (demo captions)", url: "/subs/sintel-en.vtt", kind: "captions", default: true },
    ],
    trailer: clipTrailer("Sintel-0", 30, 40),
    featured: true,
    trending: true,
    newRelease: true,
    lumoraPick: true,
    rightsNote: CC_NOTE,
    contentTier: "demo",
    daysAgo: 1,
  }),
  movie({
    slug: "tears-of-steel",
    title: "Tears of Steel",
    tagline: "The last stand begins with a memory.",
    year: 2012,
    runtime: 734,
    genres: ["scifi", "action", "drama"],
    rating: 7.0,
    popularity: 77,
    contentRating: "PG-13",
    director: "Ian Hubert",
    cast: [
      { name: "Derek de Lint", role: "Dr. Wolf" },
      { name: "Sergio Hasselbaink", role: "Thom" },
      { name: "Rogier Schippers", role: "Young Thom" },
    ],
    synopsis:
      "In a ruined future Amsterdam overrun by robots, a team of scientists tries to save the world by re-enacting the breakup that set the apocalypse in motion — inside reconstructed memories. The Blender Foundation's live-action/VFX open movie, released under CC BY 3.0.",
    releaseDate: "2012-09-26",
    archiveId: "Tears-of-Steel",
    sources: iaSources("Tears-of-Steel", [["tears_of_steel_1080p.mp4", 360]], "cc-licensed", CC_ATTR),
    subtitles: [
      { id: "tos-en", lang: "en", label: "English (demo captions)", url: "/subs/tos-en.vtt", kind: "captions", default: true },
    ],
    trailer: clipTrailer("Tears-of-Steel-0", 30, 40),
    trending: true,
    newRelease: true,
    rightsNote: CC_NOTE,
    contentTier: "demo",
    daysAgo: 1,
  }),
  movie({
    slug: "elephants-dream",
    title: "Elephants Dream",
    year: 2006,
    runtime: 654,
    genres: ["animation", "scifi", "fantasy"],
    rating: 6.9,
    popularity: 69,
    contentRating: "PG",
    director: "Bassam Kurdali",
    cast: [
      { name: "Tygo Gernandt", role: "Proog (voice)" },
      { name: "Cas Jansen", role: "Emo (voice)" },
    ],
    synopsis:
      "Two figures explore a vast, surreal machine-world where Proog sees danger at every turn and Emo sees only wonder — until their disagreement reaches a violent climax. The world's first open movie, produced entirely with free software and released by the Blender Foundation under CC BY 3.0.",
    releaseDate: "2006-03-24",
    archiveId: "ElephantsDream",
    sources: iaSources(
      "ElephantsDream",
      [
        ["ed_1024.mp4", 360],
        ["ed_1024_512kb.mp4", 240],
      ],
      "cc-licensed",
      CC_ATTR
    ),
    trailer: clipTrailer("ElephantsDream-0", 20, 40),
    newRelease: true,
    rightsNote: CC_NOTE,
    contentTier: "demo",
    daysAgo: 13,
  }),
];
